services:
  gateway:
    build: ./gateway
    ports:
      - "5000:5000"
    depends_on:
      - auth-service
      - shop-service
      - logs-service
    environment:
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - internal
  
  auth-service:
    build: ./auth-service
    environment:
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - internal
  
  shop-service:
    build: ./shop-service
    networks:
      - internal
  
  logs-service:
    build: ./logs-service
    networks:
      - internal

networks:
  internal:
    driver: bridge
