services:
  gateway:
    build: ./gateway
    ports:
      - "5000:5000"
    depends_on:
      - auth
      - shop
      - logs
    environment:
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - internal
  
  auth:
    build: ./auth
    environment:
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - internal
  
  shop:
    build: ./shop
    networks:
      - internal
  
  logs:
    build: ./logs
    networks:
      - internal

networks:
  internal:
    driver: bridge
